### ISSUE TITLE
Install node-ffi

### ISSUE THREAD

**Issue by PitterL** [mjangir/reactron#4]
Hi, Manish:
     Nice to meet you.
     Do you have suggest to install node-ffi module?
     I use the npm install ffi, it installed into "reactron\node_modules\ffi“, but when i want to import this from js file, it show the ffi file linked to "C:\Users\xxx\AppData\Local\Microsoft\TypeScript\3.0\node_modules\@types\ffi"

------------------------------
const ref = require('ref');
const ffi = require('ffi');
------------------------------
BTW, i saw there are two 
reactron\node_modules
reactron\app\node_modules

what's the different of them?

thanks

**Comment by mjangir** [comment]
This is two package.json structure suggested by electronjs itself. This structure is usually adopted when you need to ship some native node dependencies as they are with the bundled exe or dmg file.

Read more about it here:

https://www.electron.build/tutorials/two-package-structure

**Comment by PitterL** [comment]
Hi, Manish:
     I have compared with the official "electron-quick-start" project ,the ffi module is working inside(This only single node_modules dir.). So i suspect that the require() path may be different(Not really which i wanted).
     Have you got idea how to get the actual path when i call require() in reactron project?

Thanks.

**Comment by mjangir** [comment]
Perhaps I'm not understanding your concern. Could you please elaborate?

**Comment by PitterL** [comment]
Hi, Manish:
    I tested with your suggestion and found the native modules could only be used at devDependencies node_modules(the one at root directory). So for the electron two-package-structure, what's the suggested method for App layer communication with the Native layer?
   I supposed to use the 'Web Workers' to call native module and send message to App layer?

Thanks.

**Comment by PitterL** [comment]
I use the ipcMain for load ffi and send message to ipcRenderer. It' working.
